name: hasktorch
language: GHC2021

default-extensions:
  - TypeFamilies
  - DataKinds
  - GADTs
  - AllowAmbiguousTypes
  - UndecidableInstances
  - TemplateHaskell

ghc-options: -Wno-x-partial

library:
  source-dirs: lib
  dependencies:
    - base
    - vector
    - deepseq
    - template-haskell

executables:
  mnist:
    main: Main.hs
    source-dirs: app
    dependencies:
      - base
      - hasktorch
      - vector

tests:
  hasktorch-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - base
      - hasktorch
      - hspec
      - vector
      - deepseq
